version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-elben.github.io-{{ checksum "elbenshiracom.cabal" }}-{{ checksum "stack.yaml" }}
            - v1-elben.github.io-
      - run:
          name: Upgrade to the latest version of stack (Circle comes with stack pre-installed)
          command: stack upgrade
      - run:
          name: Setup GHC
          command: stack setup
      - run:
          name: Build dependencies
          command: stack build --pedantic
      - save_cache:
          key: v1-elben.github.io-{{ checksum "elbenshiracom.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
      - run: make all
  generate:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-elben.github.io-{{ checksum "elbenshiracom.cabal" }}-{{ checksum "stack.yaml" }}
            - v1-elben.github.io-
      - run:
          name: Generate the website files and push to master branch
          command: make deploy

workflows:
  version: 2
  build-generate:
    jobs:
      - build:
          filters:
            # Don't build master since that's for GitHub pages
            branches:
              ignore: master
      - generate:
          requires:
            - build
          filters:
            branches:
              # Only generate website files from the `source` branch
              only: source
