version: 2

# Based off: https://github.com/johnae/circleci-nix
references:
  prepare_ci: &prepare_container
    run:
      name: Prepare Container
      command: |
        nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
        nix-channel --update
        nix-env -iA nixpkgs.haskellPackages.cabal-install
        nix-env -i ghc
        nix-env -i gnumake

jobs:
  build:
    docker:
      # https://github.com/NixOS/docker
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - *prepare_container
      - restore_cache:
          keys:
            - v2-elben.github.io-{{ checksum "elbenshiracom.cabal" }}-{{ checksum "default.nix" }}
            - v2-elben.github.io-
      - run:
          name: Generate website
          command: make all
          no_output_timeout: 45m
      - save_cache:
          # Save the built files to be deployed later
          key: v2-elben.github.io-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - out
  deploy:
    docker:
      # https://github.com/NixOS/docker
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-elben.github.io-build-{{ .Branch }}-{{ .Revision }}
            - v2-elben.github.io-build
      - run:
          name: Deploy website
          command: make deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            # Don't build master since that's for GitHub pages
            branches:
              ignore: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              # Only deploy website files from the `source` branch
              only: source
