version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-elben.github.io-{{ checksum "elbenshiracom.cabal" }}-{{ checksum "stack.yaml" }}
            - v1-elben.github.io-
      - run:
          name: Install build essentials
          command: sudo apt-get install build-essential g++
      - run:
          name: Upgrade stack
          command: stack upgrade
      - run:
          name: Setup GHC
          command: stack setup
      - run:
          name: Build dependencies
          command: stack build --pedantic
      - save_cache:
          key: v1-elben.github.io-{{ checksum "elbenshiracom.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
      - run:
          name: Generate website
          command: make all
          no_output_timeout: 30m
      - save_cache:
          # Save the built files to be deployed later
          key: v1-elben.github.io-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - out
  deploy:
    docker:
      - image: buildpack-deps:xenial
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-elben.github.io-build-{{ .Branch }}-{{ .Revision }}
            - v1-elben.github.io-build
      - run:
          name: Deploy website
          command: make deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            # Don't build master since that's for GitHub pages
            branches:
              ignore: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              # Only deploy website files from the `source` branch
              only: source
